In [64]:
import torch
import numpy as np
temp = torch.rand(1, 2)
ft = torch.FloatTensor((1, 2))


In [2]:
import torch
import torch.nn as nn

# 입력 데이터의 크기: (배치 크기, 채널, 높이, 너비)
input_size = (64, 3, 32, 32)

# Conv2d 레이어 정의
conv = nn.Conv2d(in_channels=3, out_channels=64, kernel_size=3, stride=1, padding=1)

# 입력 데이터 생성
input_data = torch.randn(input_size)

# 컨볼루션 연산 수행
output = conv(input_data)

# 출력 데이터의 크기 출력
print("Output size:", output.size())


Output size: torch.Size([64, 64, 32, 32])


/opt/conda/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
import torch

ckpt = torch.load('/mnt/ssd_mnt/kkr/DR-DiffuSE/asset/model/DiffuSE_best.pth')
print(ckpt['step'])

11


In [6]:
ckpts = torch.load('/mnt/ssd_mnt/kkr/DR-DiffuSE/asset/log/Base_41.pth')
print(ckpts['step'])

41


In [65]:
ft

tensor([1., 2.])

In [67]:
temp_np = np.array(ft, dtype=np.uint8)
temp_np

array([1, 2], dtype=uint8)

In [53]:
temp_te = torch.from_numpy(temp_np)

In [62]:
temp_te = temp_te.to(torch.float32)

In [63]:
temp_te

tensor([[0., 0.]])